TRAIN:
  ENABLE: True
  DATASET: Moments
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 3
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /users/azerroug/data/azerroug/Moments_in_Time_256x256_30fps
RESNET:
  SHORTCUT_TYPE: 'B'
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 1e-3
  # LR_POLICY: cosine
  # MAX_EPOCH: 196
  # MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  # WARMUP_EPOCHS: 34
  # WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: adam
MODEL:
  NUM_CLASSES: 339
  ARCH: resnet18
  MODEL_NAME: GN_R3D
  LOSS_FUNC: cross_entropy # cross_entropy
  DROPOUT_RATE: 0.5
GN:
  HORIZONTAL_UNITS: [[0, 3],
                    [1, 3],
                    [2, 3],
                    [3, 3],
                    [4, 1]]
  TOPDOWN_UNITS: [[0, 1],
                  [2, 1]]
  RECURRENT_BN: 'GN'
  FEEDFORWARD_BN: 'BN'
PREDICTIVE:
  ENABLE: True
  CPC: False
TEST:
  ENABLE: True
  DATASET: Moments
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
