TRAIN:
  ENABLE: True
  DATASET: Moments
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 3
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /users/azerroug/data/azerroug/Moments_in_Time_256x256_30fps
HMDB:
  OUT_SAMPLE_RATE: 15
  ANNOTATION_PATH: /users/azerroug/data/azerroug/HMDB51/hmdb51_1.json
RESNET:
  SHORTCUT_TYPE: 'B'
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 339
  ARCH: resnet18
  MODEL_NAME: ResNet3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: Moments
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
